config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  root 'recipes#index'
  get 'pages/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
has_many :ingredients, dependent: :destroy
accepts_nested_attributes_for :ingredients, allow_destroy: true

has_many :steps, dependent: :destroy
accepts_nested_attributes_for :steps, allow_destroy: true

mount_uploader :image, ImageUploader

end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
     params.require(:recipe).permit(:remove_image, :image, :title, :description, ingredients_attributes:[:id, :content, :_destroy], steps_attributes:[:id, :direction, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Mama's Kitchen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<div class="navigation">
<nav class="navbar navbar-toggleable-md navbar-inverse bg-faded">
	<h4>
    <div class="container">
  		<%= link_to "Home", root_path, class: "navbar-brand", class: "navstyles"%>
      <div class="right">
        <%= link_to "About", pages_about_path, class: "nav-link", class: "navstyles"%>
      </div>
	 </div>
  </h4>
</nav>
</div>
<div class="container">
  <body>
    <%= yield %>
  </body>
</div>
</html>

app/views/pages/about.html.erb

<h1>About Mama's Kitchen</h1>
<div class="aboutpage">
<p>Martha Helen Stewart (née Kostyra; born August 3, 1941) is an American businesswoman, writer, and television personality. As founder of Martha Stewart Living Omnimedia, she has gained success through a variety of business ventures, encompassing publishing, broadcasting, merchandising, and e-commerce. She has written numerous bestselling books, is the publisher of the Martha Stewart Living magazine, and hosted two long-running syndicated television shows, Martha, which ran from 2005 to 2012, and Martha Stewart Living, which ran from 1993 to 2005.</p>

<p>In 2004, Stewart was convicted of charges related to the ImClone stock trading case. There was speculation that the incident would effectively end her media empire,[2][3][4] although Stewart began a comeback campaign in 2005[5] and her company returned to profitability in 2006.[6] Stewart rejoined the board of directors of Martha Stewart Living Omnimedia in 2011[7] and became chairman of her namesake company again in 2012.[8] The company was acquired by Sequential Brands in 2015.[9] </p>

<p>Stewart is currently hosting a VH1 cooking show with popular musician Snoop Dogg, entitled Martha & Snoop's Potluck Dinner Party.</p>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




<div class="titledescription">
  <div class="form-group">
    <h2>Title</h2>
    <%= form.text_field :title, id: :recipe_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <h2>Description</h2>
    <%= form.text_area :description, id: :recipe_description, class: "form-control" %>
  </div>
</div>

<div class="image">
 <div class="form-group">
<%= form.file_field :image %>
    
    <% if @recipe.image? %>
      <%= image_tag @recipe.image.url, class: "recipe-show" %>
     <%= form.check_box :remove_image %>
        Remove Image
      
    <% end %>
  </div>
 </div>
<div class="row"></div>
  <div class="formingredients">
    <div class="form-group">
      <h2>Ingredients</h2>
    <%= form.nested_fields_for :ingredients do |ingredient| %>
    <%= ingredient.text_field :content, class: "form-control" %>
    <%= ingredient.remove_nested_fields_link %>
   
    <% end %>
  </div>
<button type="button" class="btn btn-default"><%= form.add_nested_fields_link :ingredients %></button>
   
 </div>

   <div class="formsteps">
      <div class="form-group">
        <h2>Steps</h2>
          <%= form.nested_fields_for :steps do |step| %>
          <%= step.text_field :direction, class: "form-control" %>
          <%= step.remove_nested_fields_link %>
    <% end %>
     </div>
     <button type="button" class="btn btn-default"><%= form.add_nested_fields_link :steps %></button>
  
  </div>  
  
  <div class="link">
  <div class="actions">
   <%= form.submit %>
  </div>
</div>



  <% end %>

app/views/recipes/edit.html.erb
<%= render 'form', recipe: @recipe %>

<div class="link">
	<%= link_to 'View', @recipe %>
	<%= link_to 'Back', recipes_path %>

</div>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mama's Kitchen</h1>


  <thead>
    <tr>
      <th colspan="3"></th>
 
  </thead>

    <% @recipes.each do |recipe| %>

<div class="col-md-4">
  <div class="recipe-box">
    <% if recipe.image? %>
      <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
    <% end %>
<div class="container2">
        <h2><%= recipe.title %></h2>
          <div class="row"></div>
        <p><%= recipe.description %></p>

        <button type="button" class="btn btn-default"><%= link_to 'View', recipe %></button>
       <div class="editdelete">
      <%= link_to 'Edit', edit_recipe_path(recipe) %>
      <%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
</div>


  </div><!-- /recipe-box-->
</div><!--col-md-4-->
    <% end %>


<div class="col-md-4">
  <button type="button" class="btn btn-default"><h2><%= link_to 'Create a New Recipe', new_recipe_path %></h2></button>
</div>

app/views/recipes/new.html.erb
<%= render 'form', recipe: @recipe %>

<div class="link">
	<%= link_to 'Back', recipes_path %>

</div>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>



<% if @recipe.image? %>
<%= image_tag @recipe.image.url, class: "recipe-show" %>
<% end %>

<h1>
  <%= @recipe.title %>
</h1>

<h3>
  <%= @recipe.description %>
</h3>

<div class="showingredients">
<h2>Ingredients</h2>
<ul>
<% for @ingredient in @recipe.ingredients %>
<li><%= @ingredient.content %></li>
<% end %>
</ul>
</div>

<div class="showsteps">
<h2>Steps</h2>
<ol>
<% for @step in @recipe.steps %>
<li><%= @step.direction %></li>
<% end %>
</ol>
</div>

<div class="link">
	<%= link_to 'Edit', edit_recipe_path(@recipe) %>
<%= link_to 'Back', recipes_path %>

</div>